engine_type: ort

# classification model params
input_name: input
output_name: output
input_size:
- 32
- 32
input_dtype: float32
max_batchsize: 15

# yolov5 model params
yolov5_input_name: images
yolov5_output_name: output0
yolov5_input_size: 
- 640
- 640
yolov5_input_dtype: 'float32'

# for nms params 
# yolov5 needs bigger conf_thres 0.8 and classifier needs smaller conf_thres 0.2
conf_thres: 0.7
iou_thres: 0.45
enemy_armor_index_list: None
agnostic: False
max_det: 20


# this if for if_is_gray() , cause yolov5 sometimes mistinguish gray with blue and red
white_num_thresh: 5

blue_yuv_range: 
- 152
- 255
red_yuv_range: 
- 164 
- 255


