yaw_left_degree: -60.0
yaw_right_degree: 60.0
pitch_down_degree: -15.0
pitch_up_degree: 10.0
yaw_search_step: 0.01
        
pitch_search_left_waves: 5
pitch_search_right_waves: 6

        
fire_mode: 1
sleep_time_after_move_command: 0.0
repeat_times_for_move_command: 1
yaw_pitch_history_length: 20

continuous_detected_num_min_threshold: 1
continuous_lost_num_max_threshold: 8











