# for abs search
big_gimbal_major_yaw: 0.0 # rad
pitch_min: -20.0 # deg
pitch_max: 5.0  # deg
yaw_search_step: 0.2 # rad
pitch_search_step: 0.2 # rad

# In the frame of zero yaw big gimbal 

# 45.0 for Sentry Small Gimbal Right
# 180.0 for Sentry Small Gimbal Left
# 0 for Sentry Big Gimbal and White Car
yaw_mechanical_positive_limit_switch: 45 # deg
# -180.0 for Sentry Small Gimbal Right
# -45.0 for Sentry Big Gimbal Left
# 0 for Sentry Big Gimbal and White Car
yaw_mechanical_negative_limit_switch: -180 # deg



# for track and lock
continuous_detected_num_for_track: 1
continuous_lost_num_max_threshold: 15


# for ballistic
# WARN: Only fit for 640 * 384 img_show size, img_x is x,img_y is z, by default, img_y locked when img_x is locked 
min_img_x_for_locked: 40.0 # for fire_mode 1
min_continuous_detected_num_for_lock: 2
manual_pitch_compensation: 0.0 # 0.04
manual_yaw_compensation: -0.01



# for recording data
tvec_history_length: 10  
record_data_path: null
target_history_lenght: 5   # must bigger than min_continuous_detected_num_for_lock

# this is for mouse control
screen_width: 1920
screen_height: 1080
if_enable_mouse_control: False
    # 0-1, x from left to right = 100degree, y from top to bottom = 100degree
x_axis_sensitivity: 0.5
y_axis_sensitivity: 0.5


# general config

if_use_pid_control: True
fire_mode: 1 # 0 track, 1 pitch_compensation, 2 pitch_compensation with gravity compensation
choose_mode: 1 # 0 precision_first, 1 distance_first, 2 balanced


# for event,  should adjust with fps
auto_bounce_back_period: 5 # seconds, if < 0, disable auto bounce back
direction_accept_error: 0.03 # radian , around 1.5 degree 
auto_bounce_back_continue_frames: 10 
sentry_go_supply_health_threshold: 595 # 200 for Real, 595 for Debug
search_friend_yaw: -0.05 # rad , 1.5708 for Real , 0 for Debug
search_friend_pitch: -0.1745 # rad


# event_flag:
# DOING_NOTHING = 0
# SEARCH_AND_FIRE = 1
# AUTO_BOUNCE_BACK = 2, do not use this flag, enable auto_bounce_back by set auto_bounce_back_period > 0 instead
# GO_RIGHT = 3
# GO_LEFT = 4
# GO_FORWARD = 5
# GO_BACKWARD = 6
# SEARCH_FRIEND = 7 # Do not use this flag , enable if_auto_recognize_friend instead

# strategy 1, go left to protect 
strategy_0_event_flag_to_arg_list:
- - 1
  - 999
strategy_1_event_flag_to_arg_list:
- - 1
  - 1500                              # Search until race start, may pre start by sentry health
- - 4
  - 200 # 250 for real, 200 for dbg   # Go left 
- - 5
  - 50 # 100 for real, 50 for dbg     # Go forward 
- - 1
  - 1500                              # Search and fire until health is below 300, 999 for real, 1500 for dbg
- - 6
  - 125 # 175 for real , 125 for dbg # Go backward to wall 
- - 4
  - 50 # 100 for real, 50 for dbg    # Go left to wall
- - 1   
  - 1500                               # Search and fire until health is 600, 3000 for real, 1500 for dbg
- - 5
  - 100 # 150 for real, 100 for dbg   # Go forward
- - 3
  - 50 # 75 for real, 50 for dbg     # Go right 
- - 1
  - 999                               # Search and fire until race end, may pre end by sentry health

strategy_2_event_flag_to_arg_list:
- - 1
  - 1500                              # Search until race start, may pre start by sentry health      
- - 3
  - 50 # 75 for real, 50 for dbg     # Go right 
- - 5
  - 50 # 75 for real, 50 for dbg     # Go forward 
- - 1
  - 1500                             # Search and fire until health is below 300
- - 6
  - 60 # 85 for real, 60 for dbg     # Go backward 
- - 4
  - 250 # 325 for real, 250 for dbg   # Go left to wall 
- - 6
  - 125 # 175 for real, 125 for dbg   # Go backward to wall 
- - 1
  - 1500                             # Search and fire until health is 600
- - 5 
  - 100 # same as strategy_1           # Go forward 
- - 3
  - 50 # same as strategy_1           # Go right 
- - 1
  - 999                             # Search and fire until race end, may pre end by sentry health

# "0" for sentry, "1" for hero, "3","4" for infantory, "-1" for nobody
primary_target: "0"













