# for abs search
yaw_left_degree: -30.0
yaw_right_degree: 30.0
pitch_down_degree: -10.0
pitch_up_degree: 5.0
yaw_search_step: 0.02
pitch_search_left_waves: 4
pitch_search_right_waves: 5


# for relative search
relative_yaw_move_step: 0.05
relative_pitch_move_step: 0.03
yaw_idx_max: 100
pitch_idx_max: 10





# for track and lock
continuous_detected_num_for_track: 1
continuous_lost_num_max_threshold: 15


# for ballistic
# WARN: Only fit for 640 * 384 img_show size, img_x is x,img_y is z, by default, img_y locked when img_x is locked 
min_img_x_for_locked: 40.0 # for fire_mode 1
min_img_x_diff_for_predict: 10.0 # for fire_mode 2
manual_pitch_compensation: 0.04
manual_yaw_compensation: -0.01



# for recording data
tvec_history_length: 10  
record_data_path: null

# this is for mouse control
screen_width: 1920
screen_height: 1080
if_enable_mouse_control: False

    # 0-1, x from left to right = 100degree, y from top to bottom = 100degree
x_axis_sensitivity: 0.5
y_axis_sensitivity: 0.5


# general config

if_use_pid_control: True

fire_mode: 1 # 0 track, 1 pitch_compensation, 2 pitch_compensation with gravity compensation
choose_mode: 1 # 0 precision_first, 1 distance_first, 2 balanced

# for predict
yaw_pitch_history_length: 20
armor_continuous_num_for_predict: 3
predict_period: 0.0     # only work when fire_mode == 2, if > 0, use specified time to predict, if <0 , predict int(period) 1/fps time, if ==0, auto predict rely on depth
target_history_length: 5
ele_latence: 0.01 # second






