yaw_left_degree: -60.0
yaw_right_degree: 60.0
pitch_down_degree: -15.0
pitch_up_degree: 0.0
yaw_search_step: 0.03
        
pitch_search_left_waves: 5
pitch_search_right_waves: 6
fire_mode: 1
sleep_time_after_move_command: 0.0
repeat_times_for_move_command: 1
yaw_pitch_history_length: 20

continuous_detected_num_min_threshold: 2
continuous_lost_num_max_threshold: 15


relative_yaw_move_step: 0.05
relative_pitch_move_step: 0.03
relative_pitch_move_step: 0.05
yaw_idx_max: 100
pitch_idx_max: 10



# for recording data
tvec_history_length: 10  
record_data_path: null


# this is for mouse control
screen_width: 1920
screen_height: 1080
if_enable_mouse_control: False

# 0-1, x from left to right = 100degree, y from top to bottom = 100degree
x_axis_sensitivity: 0.5
y_axis_sensitivity: 0.5


if_use_pid_control: True











