# Debug modifiable value
# Q_scale : process noise parameter for Kalman filter
# R_scale_dis_diff_denominator: bigger value means R is smaller, which means trust more the measurement
# history_depth: > 3
# min_continuous_num_to_apply_predict
# min_dis_between_continous_detection
# min_time_between_continous_detection





armor_name_to_car_params: {}

history_depth: 5
continuous_detected_num_max: 15
continuous_lost_num_max: 15









