# Debug modifiable value
# Q_scale : process noise parameter for Kalman filter
# R_scale_dis_diff_denominator: bigger value means R is smaller, which means trust more the measurement
# history_depth: > 3
# min_continuous_num_to_apply_predict
# min_dis_between_continous_detection
# min_time_between_continous_detection




H:
- - 1
  - 0
  - 0
- - 0
  - 1
  - 0
- - 0
  - 0
  - 1
Q_scale: 0.1
R_scale_dis_diff_denominator: 0.1
predict_offset_time: 1.0
armor_name_to_car_params: {}

history_depth: 5
min_continuous_num_to_apply_predict: 2
min_dis_between_continous_detection: 0.1
min_time_between_continous_detection: 0.3
continuous_detected_num_max: 15
continuous_lost_num_max: 15

score_accumulation_method_list_for_automatic_matching:
- add
- add
- add



score_criterion_for_automatic_matching: 200

# armor_name, tvec, rvec, confidence
score_weights_list_for_automatic_matching:
- 100
- 10
- 0
- 0


# if > wrongpic_threshold_dis and armor_name == wrongpic, then it's a wrongpic
wrongpic_threshold_dis: 0.1

