# img_y is from -192 to 192
# Vertical Feild of View : max: -23 ~ 23,  or ~ -20 ~ 20 degree considering focal length change(-0.319 to 0.319 radian)
# x = img_x /f * deep, x / deep = img_x /f
# f = 687~775, f = 700, or img_y / f = tan(0.319) = 0.330, f = 581.32

#relative_yaw = -np.arctan(img_x / 700) 
#pid_rel_yaw = -self.yaw_pid_controller.get_output(0.0,relative_yaw)
#relative_pitch = -np.arctan(img_z / 700)
#pid_rel_pit = self.pitch_pid_controller.get_output(0.0,relative_pitch) 
                
kp: 0.8
ki: 0.0
kd: 0.2
max_output: 3.14159
min_output: -3.14159



