big_obj_points:
- - -112.5
  - -27.5
  - 0.0
- - 112.5
  - -27.5
  - 0.0
- - -112.5
  - 27.5
  - 0.0
- - 112.5
  - 27.5
  - 0.0


# 512 * 640 is 0.5 of 1024 * 1280
img_shrink_scale: 0.5


# up left/ up right/ down right/ down left
small_obj_points:
- - -67.5
  - -62.5
  - 0.0
- - 67.5
  - -62.5
  - 0.0
- - 67.5
  - 62.5
  - 0.0
- - -67.5
  - 62.5
  - 0.0


obj_wid_in_world: 135.0
obj_hei_in_world: 125.0

# pnp or pnp_fix or 2d_and_pnp
method_name: 2d_and_pnp

camera_center:
- 320.0
- 320.0

# if_yolov5, armor_name=color_id+num, color: 0=blue,1=red,2=gray;num:0 is sentry, others are itself
# e.g.: red 3x --> (in yolov5) 13
small_armor_name_list:
- 2x
- 3x
- 4x
- 5x
- basex
- sentry
- B2
- B3
- B4
- B5
- R2
- R3
- R4
- R5

# if use tradition method, you have to set expand rate in code file
expand_rate: 1.5



# good mv
dist:
- - -0.13540592406247062
  - 0.3680838553089874
  - 0.0
  - 0.0
  - 0.0
mtx:
- - 1321.4797328200445
  - 0.0
  - 621.8268939951641
- - 0.0
  - 1318.4239992887028
  - 499.15374624053845
- - 0.0
  - 0.0
  - 1.0


