
# mode: Dbg, Rel 
mode : Dbg

# gimbal_action_mode:
# 0: not test gimbal, make decision only
# 1: test gimbal, repeat what recv from electric system
# 2: test gimbal, turn around yaw
# 3: test gimbal, turn down, then turn up, then turn down, then turn horizontal
# 4: doing nothing, use rqt to control gimbal, use rqt to see target value
# 5: test_fire mode
gimbal_action_mode: 4
if_relative: False

if_ignore_elesys: True
if_show_img_local: True
if_show_img_remote: False
# enemy armor color
armor_color : blue

if_reverse_img: True



if_yolov5: True
# WARNING : armor_name depends on if_yolov5 !!!

enemy_car_list : 
- armor_distance:
  - 0.5
  - 0.5
  armor_name: B3
  armor_nums: 1  
#- armor_distance:
#  - 0.5
#  - 0.5
#  armor_name: 4x
#  armor_nums: 2

# armor_distance : the distance between 2 opposite armors, unit: m
# if armor_nums == 4: [x_distance, y_distance], x distance means maximum efficency direction of robot chassis 
# if armor_nums == 2: [no_meaning, distance] 

# in camera frame
armor_name_to_init_state:
  B3:
    rvec:
    - 0.0
    - 0.0
    - 3.141593
    tvec:
    - 0.0
    - 5.0
    - -0.3
#  2x:
#    rvec:
#    - 1
#    - 1
#    - 1
#    tvec:
#    - 1
#    - 1
#    - 1

# Warning :
# global logger level need to be set in os_op/global_logger.py


# Notice :
# rviz2 yaw = 4.72318 pitch = 0.2 , in this sight, x if right, y is in, z is up


# Notice :
# config ballistic config : gun_pivot_height !!!

img_show_wid: 640
img_show_hei: 384
node_webcam_mv_ms: 10